version: '3.8'

networks:
  network-portobrasil-esmaltacao-back:
    name: network-portobrasil-esmaltacao-back

services:
  nginx:
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    image: crmsolucoes/nginx-stable-alpine:latest
    container_name: esmaltacao_nginx
    hostname: esmaltacao_nginx
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/log:/var/log/nginx
      - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network-portobrasil-esmaltacao-back

  php:
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    image: wassonece/php-mssql:7.1-fpm-jessie
    container_name: esmaltacao_php
    hostname: esmaltacao_php
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - network-portobrasil-esmaltacao-back

  composer:
    image: composer:latest
    container_name: esmaltacao_composer
    hostname: esmaltacao_composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - network-portobrasil-esmaltacao-back
